---
on:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/pre-commit.yml@541b3d3c9182820bec7f027fb9c61a5c17974ed8" # v0.10.35
