---
on:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/pre-commit.yml@76e8800f3493921a1eeaf89e26dd97ce064f990d" # v0.10.34
