---
on:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/pre-commit.yml@959e22a07499324e8f241f57678172b35f12a9d4" # v0.10.36
