---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@959e22a07499324e8f241f57678172b35f12a9d4" # v0.10.36
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
