---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@76e8800f3493921a1eeaf89e26dd97ce064f990d" # v0.10.34
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
