---
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: "Mosher-Labs/.github/.github/workflows/release.yml@39dc1e003e0c99ee009eecca4773bb6aa4935ce2" # v0.11.1
    secrets: inherit
    permissions:
      contents: write
      issues: write
      pull-requests: write
