---
on:
  schedule:
    - cron: "21 6 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/stale.yml@563ce006b6248edecdcbe134f3a4888b7d2595f5" # v0.10.37
