---
on:
  schedule:
    - cron: "21 6 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/stale.yml@ef07cf67ff3b59d701ca4ebb5670f8579b0b0303" # v0.10.33
