---
on:
  schedule:
    - cron: "21 6 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  pre-commit:
    uses: "Mosher-Labs/.github/.github/workflows/stale.yml@959e22a07499324e8f241f57678172b35f12a9d4" # v0.10.36
